# Generated by Django 2.0.3 on 2018-04-13 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180413_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='products_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product_in_cart',
            name='guest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Guest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
