# Generated by Django 2.0.3 on 2018-04-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180415_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_photo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', unique=True),
        ),
    ]
