# Generated by Django 2.0.3 on 2018-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180417_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='booked',
            new_name='reserved',
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
    ]
