# Generated by Django 2.0.3 on 2018-04-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180417_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booked_product',
            new_name='Ordered_product',
        ),
    ]
